### ISSUE TITLE
Menu links embed content in anchor tag

### ISSUE THREAD

**Issue by WimTeuling** [CanSanchez/Metrolics#12]
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L34-L37

It will be much simpler to create a button surface that is clickable when both the icon and menu text are embedded in the anchor tag.

```
<a href="#" class="main-nav__item main-nav__item--home main-nav__item--active">
    <span class="main-nav__item__text">home</span>
     <!-- optional icon may also be solved with css only in which case 
        the span.main-nav__item__text is not necessary -->
    <i class="fa fa-home" aria-hidden="true"></i>
</a>

```

**Comment by CanSanchez** [comment]
Replaced btn code with suggested lines of code ty
