### ISSUE TITLE
Avoid the use of h2 tags for the slider content

### ISSUE THREAD

**Issue by WimTeuling** [CanSanchez/Metrolics#14]
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L62-L64

Too many headings without actual content remains problematic for SEO purposes, and in this case I would argue this is a list of items, rather than a list of headings. It will improve the overall heading outline structure.

Consider:
```
  <ul class="slider__slides">
      <li class="slide">
          <a href="#" class="slide__link">
              <img src="banner-img.jpg" alt="slider alt" class="slide__img">
              <ul class="slide__info">
                  <li class="slide__info__item">Metro Style</li>
                  <li class="slide__info__item">Retina Ready</li>
                  <li class="slide__info__item">Responsive Design</li>
              </ul>>
          </a>
      </li>
      <!-- slide -->
  </ul>
  <!-- slides -->
```

**Comment by CanSanchez** [comment]
replaced slider with this code ty
