### ISSUE TITLE
Section headings need more specificity - assign reusable classes

### ISSUE THREAD

**Issue by WimTeuling** [CanSanchez/Metrolics#18]
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L84
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L111
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L150
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L228

the subheadings for all main sections are identical, but really do need to be styled as a group, separately from other h2 tags.

Why not just write
`<h2 class="heading section__heading">`

If you need to target a specific h2 heading for one of those sections:

```
<section class="page__section page__section--services">
    <header class="services__header">
        <h2 class="heading section__heading section__heading--services">Things That We Do</h2>
        <h4 class="tagline tagline--services">Ask us what we can do for you</h4>
    </header>
```

Two advantages:
1) one class affects all section headings
2) it is possible to re-use the h2 for other headings as well.

**Comment by CanSanchez** [comment]
used recommended specificity for h2 section tags
