### ISSUE TITLE
Footer column subheadings should be tagged h3 or h4 

### ISSUE THREAD

**Issue by WimTeuling** [CanSanchez/Metrolics#19]
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L247
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L258
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L267
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L270

h2 is too high up in the document outline hierarchy. A good heading structure assists SEO, content skimming (machine readers as well), an accessibility.

**Comment by CanSanchez** [comment]
used h3 as suggested
