### ISSUE TITLE
Footer column headings require more specificity

### ISSUE THREAD

**Issue by WimTeuling** [CanSanchez/Metrolics#20]
Also refer to #18 
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L247
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L258
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L270
https://github.com/CanSanchez/Metrolics/blob/30a2aca728c8759e7773a5762e1e80236880e1b7/index.html#L267

the subheadings for all main footer columns are identical, but really do need to be styled as a group, separately from other h2 tags.

Consider 
`<h3 class="heading footer__column__heading inverted">`

**Comment by CanSanchez** [comment]
used suggested spcificity/tag ty
